/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Chillroom.glb --transform 
Files: Chillroom.glb [14.55MB] > C:\Users\alexr\Documents\Development\Lofi site\public\Chillroom-transformed.glb [3.57MB] (75%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Chillroom-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Roundcube.geometry} material={materials['Wood.006']} position={[-0.619, 1.313, 2.467]} scale={0.7} />
      <mesh geometry={nodes.Plane018.geometry} material={materials.PaletteMaterial001} position={[-1.791, 1.821, 2.546]} rotation={[0, 0.255, 0]} scale={0.6} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Wood.009']} position={[1.92, 3.96, -3.7]} />
      <mesh geometry={nodes.Plane010.geometry} material={materials['Material.012']} position={[-2.229, 4.723, 0.291]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials.PaletteMaterial003} position={[1.99, 5.37, -3.635]} />
      <mesh geometry={nodes.Circle004.geometry} material={nodes.Circle004.material} position={[-1.09, 1.822, 2.977]} rotation={[-Math.PI, 1.536, -Math.PI]} scale={0.4} />
      <mesh geometry={nodes.Cube004.geometry} material={materials['Wood wall']} position={[-2.33, 3.353, 0.098]} scale={[0.596, 1, 2.28]} />
      <mesh geometry={nodes.Bean_Bag.geometry} material={materials.Test} position={[4.39, 0, 2.24]} rotation={[0, -0.733, 0]} scale={2.2} />
      <group position={[-2.17, 4.77, 2.83]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1, 2.26, 1]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials.Carvalho} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.quadro_figura} />
      </group>
      <mesh geometry={nodes.Plane019.geometry} material={materials.PaletteMaterial002} position={[-1.791, 1.821, 2.546]} rotation={[0, 0.255, 0]} scale={0.6} />
      <group position={[-0.623, 6.308, -3.454]} rotation={[2.214, 0, 0]} scale={0.603}>
        <mesh geometry={nodes.Mesh_4.geometry} material={materials.PaletteMaterial004} />
        <mesh geometry={nodes.Mesh_5.geometry} material={materials.PaletteMaterial005} />
      </group>
      <instancedMesh args={[nodes.Mesh_3.geometry, materials.PaletteMaterial001, 8]} instanceMatrix={nodes.Mesh_3.instanceMatrix} />
    </group>
  )
}

useGLTF.preload('/Chillroom-transformed.glb')
