/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { OrbitControls } from "@react-three/drei";
import { GameLights } from "../Lights/GameLights";

export function GameRoom(props) {
  const { nodes, materials } = useGLTF("/Gaming.glb");
  return (
    <group {...props} dispose={null}>
      <GameLights />
      <OrbitControls
        makeDefault
        minDistance={1}
        // originally 10 for min
        maxDistance={25}
        maxPolarAngle={Math.PI / 2}
        // enablePan={false}
      />

      <group
        position={[2.537, -0.05, -3.478]}
        rotation={[0, -0.231, 0]}
        scale={2.064}
      >
        <skinnedMesh
          geometry={nodes.Circle011.geometry}
          material={materials["white.001"]}
          skeleton={nodes.Circle011.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Circle012.geometry}
          material={materials["white.001"]}
          skeleton={nodes.Circle012.skeleton}
        />
        <primitive object={nodes.spine} />
        <skinnedMesh
          geometry={nodes.Circle015.geometry}
          material={materials["black.002"]}
          skeleton={nodes.Circle015.skeleton}
        />
        <skinnedMesh
          geometry={nodes.Circle015_1.geometry}
          material={materials["white.001"]}
          skeleton={nodes.Circle015_1.skeleton}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane043.geometry}
        material={materials.Metal}
        position={[-2.277, 1.844, -1.428]}
        rotation={[1.341, 1.526, -1.34]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane001.geometry}
          material={materials["Black.003"]}
          position={[0.105, 0.011, -0.039]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane044.geometry}
          material={materials["Metal.001"]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials.Bg}
        position={[-3.297, 1.819, -1.511]}
        rotation={[0, -0.028, 0]}
        scale={[0.224, 0.151, 0.244]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["metal.001"]}
        position={[-3.619, 1.981, -1.512]}
        rotation={[0, -0.005, 0]}
        scale={0.3}
      >
        <group position={[0.927, 3.036, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018.geometry}
            material={materials["metal.001"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane018_1.geometry}
            material={materials.screen}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table.geometry}
        material={materials.wood}
        position={[-3.077, 1.45, -1.466]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane002.geometry}
          material={materials.wood}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sofa.geometry}
        material={materials["red.001"]}
        position={[1.896, 0, 2.726]}
        rotation={[0, -0.025, 0]}
        scale={[0.887, 1.197, 1.197]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={materials["black.001"]}
          position={[-1.362, 1.16, -0.127]}
          rotation={[-0.137, 0.699, -0.697]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={materials["black.001"]}
          position={[1.208, 1.02, -0.128]}
          rotation={[0.083, -1.261, 0.365]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Table001.geometry}
        material={materials.wood}
        position={[3.195, 0.926, 0.454]}
        rotation={[0, 0.423, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane005.geometry}
          material={materials.wood}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pipe003.geometry}
        material={materials.metal}
        position={[-3.657, 5.197, -0.023]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pipe001.geometry}
        material={materials.metal}
        position={[-3.09, 5.197, 3.989]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pipe002.geometry}
        material={materials.metal}
        position={[-3.91, 0, 1.723]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Pipe.geometry}
        material={materials.metal}
        position={[-3.91, 0, 1.859]}
      />
      <group position={[-2.822, 0, 2.81]} scale={1.134}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050.geometry}
          material={materials.black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050_1.geometry}
          material={materials["screen-arcade"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050_2.geometry}
          material={materials["arcade-header"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050_3.geometry}
          material={materials["led.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050_4.geometry}
          material={materials["led.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031.geometry}
          material={materials.grey}
          position={[0.641, 1.922, 0.463]}
          rotation={[0, 0, -0.27]}
          scale={0.691}
        >
          <group position={[0, 0.08, 0]} scale={1.447}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_1.geometry}
              material={materials["black-gloss"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_2.geometry}
              material={materials.red}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane032.geometry}
          material={materials.grey}
          position={[0.641, 1.922, -0.302]}
          rotation={[0, 0, -0.27]}
          scale={0.691}
        >
          <group position={[0, 0.08, 0]} scale={1.447}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_1.geometry}
              material={materials["black-gloss"]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder_2.geometry}
              material={materials.red}
            />
          </group>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033.geometry}
          material={materials.led}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chair.geometry}
        material={materials.metal}
        position={[-1.325, 0.284, -1.448]}
        rotation={[0, 0.348, 0]}
        scale={0.106}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle001.geometry}
          material={materials.black}
          scale={9.45}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane047.geometry}
          material={materials["red.001"]}
          position={[0, 10.019, 0]}
          rotation={[0, -0.339, 0]}
          scale={10.288}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Vert008.geometry}
            material={materials.black}
            scale={0.919}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trash.geometry}
        material={materials.grey}
        position={[-2.81, 0, -3.027]}
      />
      <group position={[-1.752, 3.844, -4]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane058.geometry}
          material={materials["black-gloss"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane058_1.geometry}
          material={materials.poster1}
        />
      </group>
      <group
        position={[0.355, 3.77, -4.007]}
        rotation={[0, 0, -0.077]}
        scale={0.845}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane059.geometry}
          material={materials["black-gloss"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane059_1.geometry}
          material={materials.poster2}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Shelf.geometry}
        material={materials.wood}
        position={[-4, 3.906, -1.647]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plate.geometry}
        material={materials["black-gloss"]}
        position={[3.644, 1.135, 0.664]}
        rotation={[0, 1.444, 0]}
        scale={0.807}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Sandwich.geometry}
        material={materials.bread}
        position={[3.631, 1.226, 0.583]}
        rotation={[0.136, 1.269, -0.038]}
        scale={0.807}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane054.geometry}
          material={materials.bread}
          position={[0, -0.076, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane055.geometry}
          material={materials.yellow}
          position={[-0.044, -0.021, 0.097]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane056.geometry}
          material={materials.yellow}
          position={[-0.044, -0.012, 0.097]}
          rotation={[0.039, 0.341, -0.012]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cable005.geometry}
        material={materials["black-gloss"]}
        position={[-3.593, 0, 1.928]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper001.geometry}
        material={materials.white}
        position={[3.604, 1.005, 0.655]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper002.geometry}
        material={materials.white}
        position={[3.5, 1.009, 0.648]}
        rotation={[0, 0.258, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Paper003.geometry}
        material={materials.white}
        position={[3.213, 1.011, 0.498]}
        rotation={[0, -0.875, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane078.geometry}
        material={materials.black}
        position={[-3.546, 3.991, -0.373]}
        rotation={[0, 0.15, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane079.geometry}
          material={materials["black-gloss"]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane080.geometry}
        material={materials.black}
        position={[-3.575, 3.991, -3.541]}
        rotation={[0, -0.394, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane081.geometry}
          material={materials["black-gloss"]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cable.geometry}
        material={materials["black-gloss"]}
        position={[-3.915, 4.399, -0.349]}
      />
      <group
        position={[2.817, 1.066, 0.337]}
        rotation={[0, 1.306, -Math.PI]}
        scale={[1.143, 0.672, 0.902]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[2.795, 1.188, 0.39]}
        rotation={[-3.142, 1.48, 0]}
        scale={[0.961, 1.06, 0.961]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Lamp.geometry}
        material={materials.red}
        position={[-3.582, 1.775, -3.592]}
        rotation={[0, 1.3, 0]}
        scale={1.081}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle005.geometry}
          material={materials.red}
          position={[0, 1.304, 0.476]}
          rotation={[-0.445, 0, 0]}
          scale={1.123}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert012.geometry}
          material={materials["black-gloss"]}
          position={[0, 0.062, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials["black-gloss"]}
        position={[-0.038, -5.451, -0.035]}
        scale={[0.82, 1.55, 0.85]}
      />
      <group position={[-3.721, 4.303, -0.888]} rotation={[1.421, -1.571, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.276, -1.001]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.902, 0.672, 0.902]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.291, -1.123]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.961, 1.06, 0.961]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.348, -1.204]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1.143, 0.672, 0.902]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.291, -1.326]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.961, 1.06, 0.961]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.315, -1.468]}
        rotation={[1.695, -Math.PI / 2, 0]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.276, -1.575]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.902, 0.672, 0.902]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.291, -1.697]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.961, 1.06, 0.961]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.348, -1.777]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[1.143, 0.672, 0.902]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.291, -1.899]}
        rotation={[Math.PI / 2, -Math.PI / 2, 0]}
        scale={[0.961, 1.06, 0.961]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.721, 4.354, -2.071]}
        rotation={[1.933, -Math.PI / 2, 0]}
        scale={[1.143, 0.672, 0.902]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.543, 4.094, -2.624]}
        rotation={[0, 1.182, -Math.PI]}
        scale={[0.961, 1.06, 0.961]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.521, 4.174, -2.677]}
        rotation={[0, 1.306, -Math.PI]}
        scale={[1.143, 0.672, 0.902]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <group
        position={[-3.543, 4.296, -2.624]}
        rotation={[-3.142, 1.48, 0]}
        scale={[0.961, 1.06, 0.961]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_1.geometry}
          material={materials.book}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067_2.geometry}
          material={materials.white}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_1.geometry}
        material={materials.wall}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane_2.geometry}
        material={materials.floor}
      />
    </group>
  );
}

useGLTF.preload("/Gaming.glb");
