/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Canvas } from "@react-three/fiber";
import { OrbitControls } from "@react-three/drei";

import { useGLTF, useScroll } from "@react-three/drei";
import { useThree } from "@react-three/fiber";
import { useControls } from "leva";
import { Journal } from "../Interactables/Journal";
import { Clock } from "../Interactables/Clock";
import { PerspectiveCamera } from "@react-three/drei";
import { useState } from "react";

export function Model(props) {
  const { nodes, materials } = useGLTF("/Cozy1.glb");
  const { size } = useThree();
  const aspect = size.width / size.height;

  const [isFocused, setIsFocused] = useState(false);

  const { position } = useControls({
    position: {
      value: { x: -0.76, y: 6.19, z: -3.31 },
      step: 0.01,
    },
  });

  const clockCameraProps = {
    fov: 75,
    aspect,
    near: 0.1,
    far: 1000,
    position: [3.4, 2.7, -2.3], // Adjust camera position as needed
  };

  const handleFocus = (bool) => {
    console.log("handle focus");
    setIsFocused(bool);
    console.log(isFocused);
  };

  return (
    <group {...props} dispose={null}>
      <Journal />
      <Clock
        isFocused={isFocused}
        setIsFocused={handleFocus}
        clockActive={props.clockActive}
        setClockActive={props.setClockActive}
        clockTimes={props.clockTimes}
        setClockTimes={props.setClockTimes}
        timerText={props.timerText}
        setTimerText={props.setTimerText}
      />
      {!isFocused && (
        <OrbitControls
          makeDefault
          minDistance={1}
          // originally 10 for min
          maxDistance={25}
          maxPolarAngle={Math.PI / 2}
          // enablePan={false}
        />
      )}

      {/* <BakeShadows /> */}
      {/* <SoftShadows size={ 25 } samples={ 10 } focus={ 0 } /> */}

      {isFocused && <PerspectiveCamera makeDefault {...clockCameraProps} />}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube.geometry}
        material={materials.ChairLeg}
        position={[-0.619, 1.313, 2.467]}
        scale={0.7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube001.geometry}
        material={materials.ChairLeg}
        position={[-0.689, 0.499, 2.417]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials["Red.001"]}
        position={[-1.791, 1.821, 2.546]}
        rotation={[0, 0.255, 0]}
        scale={0.6}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle002.geometry}
          material={materials.Black}
          position={[0.295, 0.264, -0.613]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle003.geometry}
          material={materials.Black}
          position={[0.295, 0.2, -0.333]}
          scale={0.579}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane019.geometry}
          material={materials["Material.008"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane020.geometry}
          material={materials.Black}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane021.geometry}
          material={materials["Black.002"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane022.geometry}
          material={materials["Red.001"]}
          position={[-0.044, 0.899, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert005.geometry}
          material={materials.Metal}
          position={[-0.098, 0.807, -0.705]}
          rotation={[-0.303, 0, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials.Material}
        position={[1.75, 5.31, 0]}
        scale={[1.075, 18.47, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Material.001"]}
        position={[1.49, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={materials["Material.001"]}
        position={[1.92, 3.96, -3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube002.geometry}
        material={materials.ChairLeg}
        position={[1.92, 3.96, -3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube003.geometry}
        material={materials["Material.001"]}
        position={[1.9, 3.96, -3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Material.001"]}
        position={[-1.321, 0.02, 1.361]}
        scale={0.7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials.ChairLeg}
        position={[-0.941, 0.02, 1.361]}
        scale={0.7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials["Material.001"]}
        position={[-1.301, 0.02, 1.361]}
        scale={0.7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Material.001"]}
        position={[0.785, 0.001, 0.893]}
        rotation={[0, 0.193, 0]}
        scale={0.7}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane007.geometry}
          material={materials.Wall}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane012.geometry}
          material={materials["Material.001"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane013.geometry}
          material={materials["Material.001"]}
          position={[0.795, 1.807, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane077.geometry}
          material={materials.Wall}
          position={[0.078, 0.007, 0.515]}
          rotation={[Math.PI, -0.716, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane084.geometry}
          material={materials.Wall}
          position={[0.113, 0.007, -0.44]}
          rotation={[Math.PI, -0.733, Math.PI]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane085.geometry}
          material={materials.Wall}
          position={[-0.023, 0.009, -0.182]}
          rotation={[0, 1.361, 0]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle.geometry}
        material={materials["Material.003"]}
        position={[5.021, 0.001, 3.141]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Material.001"]}
        position={[-1.529, 0, -2.41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Material.001"]}
        position={[-1.419, 0, -2.41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Material.012"]}
        position={[-2.229, 4.723, 0.291]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Material.013"]}
        position={[-2.159, 4.107, 2.7]}
        rotation={[0.154, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials.Wall}
        position={[-0.677, 1.243, 2.517]}
        scale={0.7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials.Wall}
        position={[-0.677, 0.489, 2.497]}
        scale={0.7}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube005.geometry}
        material={materials["Material.004"]}
        position={[1.99, 5.37, -3.635]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials.ChairLeg}
        position={[-1.549, 0, -2.41]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials.Floor}
        position={[1.67, 0, 0]}
        scale={[1.048, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert006.geometry}
        material={materials.Black}
        position={[-1.712, 2.155, 2.661]}
        scale={0.6}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials["White gloss"]}
        position={[-2.206, 2.33, 1.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle004.geometry}
        material={nodes.Circle004.material}
        position={[-1.09, 1.822, 2.977]}
        rotation={[-Math.PI, 1.536, -Math.PI]}
        scale={0.4}
      >
        <group
          position={[-0.087, 0.434, 0.089]}
          rotation={[0.45, -0.708, 0.309]}
          scale={1.444}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_12.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_13.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_14.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_15.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_16.geometry}
            material={materials.Black}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane025.geometry}
          material={materials.Red}
          position={[-0.041, 0.775, -0.226]}
          rotation={[1.293, -0.053, -0.76]}
          scale={0.634}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cylinder004.geometry}
            material={materials.Metal}
            position={[0, 0, 0.197]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Plane024.geometry}
            material={materials.Metal}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle007.geometry}
        material={materials.Red}
        position={[-1.723, 1.854, -0.075]}
        rotation={[0, -0.601, 0]}
        scale={0.5}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle008.geometry}
          material={materials.Red}
          position={[0.925, 2.591, 0]}
          rotation={[0.004, -0.002, -0.52]}
          scale={0.937}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle010.geometry}
          material={materials.Metal}
          position={[-0.238, 0.32, 0]}
          rotation={[0, -0.65, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert007.geometry}
          material={materials.Black}
          position={[-0.238, 0.32, 0]}
          scale={1.304}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials.Black}
        position={[-0.814, 1.791, 1.356]}
        scale={0.7}
      >
        <group
          position={[0.199, 0.245, -0.707]}
          rotation={[-0.142, -0.357, Math.PI / 2]}
          scale={1.359}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_21.geometry}
            material={materials["Material.005"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_22.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_23.geometry}
            material={materials["Material.006"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_24.geometry}
            material={materials["Material.007"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_25.geometry}
            material={materials.Black}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane027.geometry}
          material={nodes.Plane027.material}
          position={[-0.002, 0.097, 0]}
          scale={0.7}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane028.geometry}
          material={materials.White}
          position={[-0.002, 0.136, 0]}
          scale={0.7}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle011.geometry}
        material={materials["White gloss"]}
        position={[-0.784, 1.852, -0.03]}
        rotation={[0, 0.479, 0]}
        scale={0.55}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle012.geometry}
          material={materials["White gloss"]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle013.geometry}
        material={materials["Material.003"]}
        position={[0.384, 2.485, -3.45]}
        scale={0.872}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle014.geometry}
          material={nodes.Circle014.material}
          scale={0.924}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane045.geometry}
          material={materials.Plant}
          position={[0, 0.429, 0]}
          scale={[1.428, 1.148, 1.428]}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials.bg}
        position={[-1.501, 3.792, -1.881]}
        scale={0.691}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane029.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials.bg}
        position={[-1.631, 3.798, -2.34]}
        rotation={[0.159, 0, 0]}
        scale={0.62}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane031.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials.bg}
        position={[-1.715, 3.792, -2.897]}
        scale={0.62}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane033.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials.bg}
        position={[-1.735, 1.369, -2.59]}
        scale={0.691}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane035.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane038.geometry}
        material={materials.bg}
        position={[-1.774, 1.388, -3.054]}
        rotation={[0.159, 0, 0]}
        scale={0.62}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane037.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane040.geometry}
        material={materials.bg}
        position={[-1.585, 1.369, -2.2]}
        scale={0.606}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane039.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane042.geometry}
        material={materials.bg}
        position={[-1.367, 2.771, -2.906]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.691, 0.863, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane041.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane044.geometry}
        material={materials.bg}
        position={[-1.392, 3.149, -2.906]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.691, 0.863, 0.691]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane043.geometry}
          material={materials.White}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle015.geometry}
        material={nodes.Circle015.material}
        position={[5.011, 0.001, 3.141]}
        scale={0.75}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert008.geometry}
        material={materials.Plant}
        position={[5.298, 0.886, 3.037]}
        rotation={[0, 0.41, 0]}
        scale={0.8}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane046.geometry}
          material={materials.Plant}
          position={[0.009, 0.547, -0.062]}
          rotation={[-0.616, -0.17, -0.119]}
          scale={0.436}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane047.geometry}
          material={materials.Plant}
          position={[-0.061, 0.547, -0.012]}
          rotation={[-1.209, 0.916, 1.125]}
          scale={0.436}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane048.geometry}
          material={materials.Plant}
          position={[0.062, 0.547, 0.005]}
          rotation={[-1.781, -0.949, -1.827]}
          scale={0.436}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane049.geometry}
          material={materials.Plant}
          position={[-0.061, 1.036, -0.236]}
          rotation={[-1.667, 0.916, 1.125]}
          scale={0.385}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane050.geometry}
          material={materials.Plant}
          position={[0.009, 1.036, -0.285]}
          rotation={[-1.074, -0.17, -0.119]}
          scale={0.385}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane051.geometry}
          material={materials.Plant}
          position={[0.062, 1.036, -0.218]}
          rotation={[-2.239, -0.949, -1.827]}
          scale={0.385}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane052.geometry}
          material={materials.Plant}
          position={[-0.061, 1.34, -0.544]}
          rotation={[-1.362, 0.916, 1.125]}
          scale={0.316}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane053.geometry}
          material={materials.Plant}
          position={[0.009, 1.34, -0.593]}
          rotation={[-0.769, -0.17, -0.119]}
          scale={0.316}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane054.geometry}
          material={materials.Plant}
          position={[0.062, 1.34, -0.526]}
          rotation={[-1.934, -0.949, -1.827]}
          scale={0.316}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane055.geometry}
          material={materials.Plant}
          position={[-0.047, 1.683, -0.705]}
          rotation={[-0.912, 0.916, 1.125]}
          scale={0.279}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane056.geometry}
          material={materials.Plant}
          position={[0.006, 1.68, -0.745]}
          rotation={[-0.32, -0.17, -0.119]}
          scale={0.279}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane057.geometry}
          material={materials.Plant}
          position={[0.048, 1.685, -0.693]}
          rotation={[-1.484, -0.949, -1.827]}
          scale={0.279}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane058.geometry}
          material={materials.Plant}
          position={[0.006, 1.789, -0.776]}
          scale={0.277}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert004.geometry}
        material={materials.Plant}
        position={[4.926, 0.886, 3.491]}
        rotation={[0, 1.311, 0]}
        scale={0.8}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane059.geometry}
          material={materials.Plant}
          position={[-0.061, 0.547, -0.012]}
          rotation={[-1.209, 0.916, 1.125]}
          scale={0.436}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane060.geometry}
          material={materials.Plant}
          position={[0.009, 0.547, -0.062]}
          rotation={[-0.616, -0.17, -0.119]}
          scale={0.436}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane061.geometry}
          material={materials.Plant}
          position={[0.062, 0.547, 0.005]}
          rotation={[-1.781, -0.949, -1.827]}
          scale={0.436}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane062.geometry}
          material={materials.Plant}
          position={[-0.061, 1.036, -0.236]}
          rotation={[-1.667, 0.916, 1.125]}
          scale={0.385}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane063.geometry}
          material={materials.Plant}
          position={[0.009, 1.036, -0.285]}
          rotation={[-1.074, -0.17, -0.119]}
          scale={0.385}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane064.geometry}
          material={materials.Plant}
          position={[0.062, 1.036, -0.218]}
          rotation={[-2.239, -0.949, -1.827]}
          scale={0.385}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane065.geometry}
          material={materials.Plant}
          position={[-0.061, 1.34, -0.544]}
          rotation={[-1.362, 0.916, 1.125]}
          scale={0.316}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane066.geometry}
          material={materials.Plant}
          position={[0.009, 1.34, -0.593]}
          rotation={[-0.769, -0.17, -0.119]}
          scale={0.316}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane067.geometry}
          material={materials.Plant}
          position={[0.062, 1.34, -0.526]}
          rotation={[-1.934, -0.949, -1.827]}
          scale={0.316}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane068.geometry}
          material={materials.Plant}
          position={[-0.047, 1.683, -0.705]}
          rotation={[-0.912, 0.916, 1.125]}
          scale={0.279}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane069.geometry}
          material={materials.Plant}
          position={[0.006, 1.68, -0.745]}
          rotation={[-0.32, -0.17, -0.119]}
          scale={0.279}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane070.geometry}
          material={materials.Plant}
          position={[0.048, 1.685, -0.693]}
          rotation={[-1.484, -0.949, -1.827]}
          scale={0.279}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Plane071.geometry}
          material={materials.Plant}
          position={[0.006, 1.789, -0.776]}
          scale={0.277}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle016.geometry}
        material={materials["Material.003"]}
        position={[-1.399, 5.122, -1.834]}
        rotation={[0, 0.62, 0]}
        scale={1.082}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle017.geometry}
          material={nodes.Circle017.material}
          scale={0.924}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert009.geometry}
          material={materials.Plant}
          position={[-0.196, 0.371, -0.057]}
          rotation={[Math.PI / 2, 0, -3.016]}
          scale={0.566}
        >
          <lineSegments
            geometry={nodes.BezierCurve.geometry}
            material={nodes.BezierCurve.material}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={2.012}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert010.geometry}
          material={materials.Plant}
          position={[0.075, 0.371, -0.105]}
          rotation={[Math.PI / 2, 0, 2.663]}
          scale={0.678}
        >
          <lineSegments
            geometry={nodes.BezierCurve001.geometry}
            material={nodes.BezierCurve001.material}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={2.012}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle018.geometry}
        material={nodes.Circle018.material}
        position={[-3.106, 2.601, 0.802]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube003.geometry}
        material={materials["Material.002"]}
        position={[-3.105, 3.601, 0.908]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube004.geometry}
        material={materials["Material.002"]}
        position={[-2.964, 3.562, 0.857]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube005.geometry}
        material={materials["Material.002"]}
        position={[-3.073, 3.616, 0.733]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube007.geometry}
        material={materials["Material.002"]}
        position={[-2.923, 3.682, 0.647]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube008.geometry}
        material={materials["Material.002"]}
        position={[-2.828, 3.562, 0.714]}
        scale={0.646}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube009.geometry}
        material={materials["Material.002"]}
        position={[-2.823, 3.638, 0.572]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube010.geometry}
        material={materials["Material.002"]}
        position={[-2.978, 3.644, 0.513]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube011.geometry}
        material={materials["Material.002"]}
        position={[-3.062, 3.608, 0.603]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube012.geometry}
        material={materials["Material.002"]}
        position={[-3.199, 3.551, 0.671]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube013.geometry}
        material={materials["Material.002"]}
        position={[-3.215, 3.595, 0.835]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube014.geometry}
        material={materials["Material.002"]}
        position={[-3.199, 3.49, 0.973]}
        scale={0.808}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube016.geometry}
        material={materials["Material.002"]}
        position={[-2.902, 3.369, 0.755]}
        scale={0.538}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Roundcube018.geometry}
        material={materials["Material.002"]}
        position={[-2.923, 3.296, 0.875]}
        scale={0.742}
      />
      <group
        position={[4.988, 4.736, -3.7]}
        rotation={[Math.PI / 2, 0.281, 0]}
        scale={0.413}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_1.geometry}
          material={materials.star}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_2.geometry}
          material={materials.ChairLeg}
        />
      </group>
      <group
        position={[5.59, 5.314, -3.63]}
        rotation={[Math.PI / 2, -0.165, 0]}
        scale={0.223}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_3.geometry}
          material={materials.star}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_4.geometry}
          material={materials.ChairLeg}
        />
      </group>
      <group
        position={[5.417, 3.827, -3.7]}
        rotation={[Math.PI / 2, -0.583, 0]}
        scale={0.32}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_5.geometry}
          material={materials.star}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_6.geometry}
          material={materials.ChairLeg}
        />
      </group>
      <group
        position={[5.722, 3.245, -3.62]}
        rotation={[Math.PI / 2, 0.312, 0]}
        scale={0.189}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_7.geometry}
          material={materials.star}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_8.geometry}
          material={materials.ChairLeg}
        />
      </group>
      <group
        position={[4.799, 2.901, -3.61]}
        rotation={[Math.PI / 2, -0.24, 0]}
        scale={0.132}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_9.geometry}
          material={materials.star}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Star_10.geometry}
          material={materials.ChairLeg}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Vert012.geometry}
        material={materials["Black.001"]}
        position={[-1.074, 6.459, -3.454]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle019.geometry}
          material={materials.Metal}
          position={[-0.014, -0.086, -0.029]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle020.geometry}
          material={materials.Metal}
          position={[6.529, -0.168, -0.029]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle021.geometry}
          material={materials.Metal}
          position={[4.762, 0.066, -0.029]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Circle022.geometry}
          material={materials.Metal}
          position={[2.185, -0.034, -0.029]}
        />
        <group
          position={[0.451, -0.152, 0]}
          rotation={[2.214, 0, 0]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_87.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_88.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_89.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[1.044, -0.161, 0]}
          rotation={[2.244, -0.274, 0.212]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_90.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_91.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_92.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[1.643, -0.071, 0]}
          rotation={[2.262, -0.346, 0.274]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_93.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_94.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_95.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[2.205, 0.019, 0]}
          rotation={[2.239, 0.251, -0.193]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_96.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_97.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_98.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[2.816, -0.125, 0]}
          rotation={[2.248, -0.291, 0.227]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_99.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_100.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_101.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[3.508, -0.201, 0]}
          rotation={[2.242, 0.266, -0.206]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_1.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_2.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Sphere_3.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[4.124, -0.058, 0]}
          rotation={[2.214, 0, 0]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_102.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_103.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_104.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[4.731, 0.114, 0]}
          rotation={[2.23, 0.201, -0.153]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_105.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_106.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_107.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[5.316, -0.004, 0]}
          rotation={[2.246, -0.283, 0.22]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_108.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_109.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_110.geometry}
            material={materials["Material.010"]}
          />
        </group>
        <group
          position={[5.985, -0.125, 0]}
          rotation={[2.228, 0.191, -0.146]}
          scale={0.603}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_111.geometry}
            material={materials.Metal}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_112.geometry}
            material={materials["Material.009"]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Mesh_113.geometry}
            material={materials["Material.010"]}
          />
        </group>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane078.geometry}
        material={materials["Material.007"]}
        position={[-2.136, 5.035, 3.574]}
        rotation={[-0.607, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane079.geometry}
        material={materials["Material.007"]}
        position={[-2.146, 5.254, 2.226]}
        rotation={[1.075, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane080.geometry}
        material={materials["Material.007"]}
        position={[-2.126, 3.284, 1.901]}
        rotation={[2.547, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane081.geometry}
        material={materials["Material.007"]}
        position={[-2.146, 2.962, 3.203]}
        rotation={[0.992, 0, 0]}
      />
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials.Wall}
        position={[-2.33, 3.353, 0.098]}
        scale={[0.596, 1, 2.28]}
      />
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes.Cube006.geometry}
        material={materials.Wall}
        position={[5.13, 3.332, -3.779]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.596, 1, 0.561]}
      />
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes.Cube007.geometry}
        material={materials.Wall}
        position={[-1.52, 3.332, -3.779]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.596, 1, 0.646]}
      />
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={materials.Wall}
        position={[1.89, 5.884, -3.779]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.596, 0.046, 1.348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube009.geometry}
        material={nodes.Cube009.material}
        position={[1.905, 5.864, -3.914]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.596, 0.061, 1.348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube010.geometry}
        material={materials["Material.001"]}
        position={[1.9, 3.96, -3.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube011.geometry}
        material={materials["Material.001"]}
        position={[3.967, 3.975, -3.651]}
      />
      <mesh
        // castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={materials["Wall.001"]}
        position={[1.89, 1.104, -3.779]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[0.596, 0.33, 1.348]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        rotation={[Math.PI / 2, -0.117, -1.669]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        material={nodes.Cube016.material}
        position={[9.601, 0, -8.683]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[-1.399, 5.122, -1.834]}
        rotation={[0, 0.62, 0]}
        scale={1.082}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Vert002.geometry}
          material={materials["Plant.002"]}
          position={[-0.196, 0.371, -0.057]}
          rotation={[Math.PI / 2, 0, -3.016]}
          scale={0.566}
        >
          <lineSegments
            geometry={nodes.BezierCurve003.geometry}
            material={nodes.BezierCurve003.material}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={2.012}
          />
        </mesh>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[-0.523, 1.926, 1.225]}
        rotation={[-0.166, 0, -0.058]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        material={nodes.Cube.material}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube012.geometry}
        material={nodes.Cube012.material}
        position={[-6.614, -0.962, 20.519]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[9.037, -9.115, -1.017]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[0.532, -11.401, 15.604]}
      />
    </group>
  );
}

useGLTF.preload("/Cozy1.glb");
